---
- hosts:
  - tag_GroupType_${grp_name}-app
  user: ubuntu
  sudo: True
  connection: paramiko
  gather_facts: false

  vars_files:
    - "../vars/app_common.yml"
    - [ "../vars/app_${deployment}.yml" ]

  tasks:
  - name: Add | nginx repo
    action: apt_repository repo=ppa:nginx/stable state=present

  - name: Update | apt repo
    command: /usr/bin/apt-get update

  - name: Install | apt-get dependencies
    action: apt pkg=$item state=installed
    with_items:
    - python-software-properties
    - python-pip
    - python-dev
    - git
    - uwsgi
    - uwsgi-plugin-python
    - libpq-dev
    - nginx

  - name: Install | pip dependencies
    action: pip name=${item}
    with_items:
    - psycopg2
    - django
    - bottle

  - name: Write | nginx.conf
    action: template src=../templates/nginx.j2 dest=/etc/nginx/nginx.conf

  - name: Copy | uwsgi
    action: copy src=../config/uwsgi.conf dest=/etc/init/uwsgi.conf

  - name: Reload | init
    command: initctl reload-configuration

  - name: Enforce | python27 for uwsgi
    command: update-alternatives --set uwsgi /usr/bin/uwsgi_python27

  - name: Delete | default nginx site
    action: file path=/etc/nginx/sites-enabled/default state=absent