---
- name: Set up the fireball transport
  hosts: tag_GroupType_${grp_name}-db
  gather_facts: False
  connection: paramiko
  user: ubuntu
  sudo: True

  tasks:
  - action: fireball

- name: Setup DB
  hosts: tag_GroupType_${grp_name}-db
  connection: fireball
  gather_facts: False

  vars:
  - db_conf: "/etc/postgresql/9.1/main/postgresql.conf"
  - db_hba: "/etc/postgresql/9.1/main/pg_hba.conf"

  vars_files:
  - "../vars/global.yml"

  tasks:
  - name: Update | apt cache
    action: apt update_cache=yes

  - name: Install | dependencies
    action: apt pkg=${item}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: Allow access to internal hosts
    action: shell sed -ie "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/9.1/main/postgresql.conf

  - name: Allow access to internal hosts
    action: shell sed -i -e '$ a host    all             all             10.0.0.0/8            md5' /etc/postgresql/9.1/main/pg_hba.conf

  - name: Restart | postgresql
    action: service name=postgresql state=restarted

#This runs in its own section because we are now using the postgres user
- name: Create DB and User
  hosts: tag_GroupType_${grp_name}-db
  gather_facts: False
  connection: paramiko
  user: ubuntu
  sudo_user: postgres
  sudo: True

  vars_files:
    - "../vars/global.yml"
    - "../vars/db_common.yml"
    - [ "../vars/db_${deployment}.yml" ]

  tasks:
  - name: Create | database
    action: postgresql_db db="${dbname}"

  - name: Allow | access to database
    action: postgresql_user db="${dbname}" user="${dbuser}" password="${dbpassword}" priv=ALL

  - name: Check | user does not have unnecessary privilege
    action: postgresql_user user="${dbuser}" role_attr_flags=NOSUPERUSER,NOCREATEDB
