---
- hosts: tag_GroupType_${grp_name}-db
  user: ubuntu
  sudo: True
  gather_facts: False

  tasks:
  - name: Update | apt cache
    action: apt update_cache=yes

  - name: Install | dependencies
    action: apt pkg=${item}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

- hosts: tag_GroupType_${grp_name}-db
  user: ubuntu
  sudo: True
  sudo_user: postgres
  gather_facts: False

  vars_files:
    - "../vars/db_common.yml"
    - [ "../vars/db_${deployment}.yml" ]

  tasks:
  - name: Create | database
    action: postgresql_db db="${dbname}"

  - name: Allow | access to database
    action: postgresql_user db="${dbname}" user="${dbuser}" password="${dbpassword}" priv=ALL

  - name: Check | user does not have unnecessary privilege
    action: postgresql_user user="${dbuser}" role_attr_flags=NOSUPERUSER,NOCREATEDB
