---
- hosts:
  - 127.0.0.1
  connection: local
  gather_facts: False

  tasks:
  - name: Delete Security Group
    action: shell euca-delete-group "${grp_name}"

  - name: Delete Private Key
    action: file dest="~/.ssh/${grp_name}.pem" state=absent

  - name: Delete Key Pair
    action: shell euca-delete-keypair ${grp_name}
