---
- name: Install Fireball Mode Dependencies
  hosts: tag_Group_${grp_name}
  user: ubuntu
  sudo: True
  gather_facts: False
  connection: paramiko

  tasks:
  - name: Update | apt repo
    command: /usr/bin/apt-get update

  - action: apt pkg=$item state=installed
    with_items:
    - python-software-properties
    - gcc
    - libzmq-dev
    - python-pip
    - python-dev

  - action: easy_install name=pip
  - action: pip name=$item state=present
    with_items:
    - pyzmq
    - pyasn1
    - PyCrypto
    - python-keyczar