---
- hosts:
  - key_${grp_name}
  user: ubuntu
  gather_facts: False

  tasks:
   - name: Output Instance Info
     local_action: debug msg="Terminating Instance [$ec2_tag_Name] ($ec2_id)"

   - name: Terminate Instance
     local_action: shell euca-terminate-instances $ec2_id
