---
- name: Set up the fireball transport
  hosts: tag_GroupType_${grp_name}-app
  gather_facts: False
  connection: paramiko
  user: ubuntu
  sudo: True

  tasks:
  - action: fireball

- name: Update MyApp
  hosts: tag_GroupType_${grp_name}-app
  connection: fireball
  gather_facts: false

  vars_files:
    - "../vars/global.yml"
    - "../vars/app_common.yml"
    - [ "../vars/app_${deployment}.yml" ]

  tasks:
  - name: Stop | services
    action: service name=${item} state=stopped
    with_items:
    - nginx
    - uwsgi

  - name: Create | /var/www
    action: file path=/var/www state=directory owner=ubuntu group=ubuntu

  - name: Copy | static
    local_action: command rsync -a -e "ssh -i ${privkey} -o 'StrictHostKeyChecking no'" ../website/ ubuntu@${inventory_hostname}:/var/www

  - name: Copy | django_site
    local_action: command rsync -a -e "ssh -i ${privkey} -o 'StrictHostKeyChecking no'" ../django_site/ ubuntu@${inventory_hostname}:/opt/apps/test

  - name: Get | userdatadir
    action: userdata
    register: ud

  - name: Sync | myapp db from app1
    action: command python manage.py syncdb --noinput chdir=/opt/apps/test
    when_string: ${ud.user_data.name} == 'app1'

  - name: Start | services
    action: service name=${item} state=started
    with_items:
    - uwsgi
    - nginx    